#!/usr/bin/env python3
import IoProto
import Joystick
import time

bio = IoProto.Boat(port='/dev/ttyUSB0')
joystick = Joystick.Device(dev='/dev/input/js0', axis_throttle=1, axis_rudder=0)

while True:
    joystick.update()
    th = joystick.throttle()
    rd = joystick.rudder()
    print("throttle: {} / rudder: {}".format(th, rd))
    bio.send(th, rd)
    time.sleep(0.01)
