#!/usr/bin/env python3
import IoProto
import time

port = '/dev/ttyUSB0'
bio = IoProto.Boat(port)

while True:
    for p in list(range(-60, +60)) + list(reversed(range(-60, +60))):
        bio.send(0, p, output=True)
        time.sleep(0.05)
